# Generated by Django 5.2.6 on 2025-09-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255, verbose_name="Ответ")),
                (
                    "correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
            ],
            options={
                "verbose_name": "Правильный ответ",
                "verbose_name_plural": "Правильные ответы",
            },
        ),
        migrations.CreateModel(
            name="EducationalModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название модуля",
                        max_length=150,
                        verbose_name="Название образовательного модуля",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True",
                        help_text="Введите описание модуля",
                        null="True",
                        verbose_name="Описание образовательного модуля",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательный модуль",
                "verbose_name_plural": "Образовательные модули",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название занятия",
                        max_length=150,
                        verbose_name="Название занятия",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True",
                        help_text="Введите описание занятия",
                        null="True",
                        verbose_name="Описание занятия",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        help_text="Добавьте ссылку на урок",
                        verbose_name="Ссылка на урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Занятие",
                "verbose_name_plural": "Занятия",
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
            },
        ),
        migrations.CreateModel(
            name="StudentAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верно"),
                ),
                (
                    "count_of_questions",
                    models.IntegerField(
                        default=0, verbose_name="Количество вопросов теста"
                    ),
                ),
                (
                    "count_of_correct_answers",
                    models.IntegerField(
                        default=0, verbose_name="Количество правильных ответов"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ студента",
                "verbose_name_plural": "Ответы студента",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название темы",
                        max_length=150,
                        verbose_name="Название темы",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank="True",
                        help_text="Введите описание темы",
                        null="True",
                        verbose_name="Описание темы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательная тема",
                "verbose_name_plural": "Образовательные темы",
            },
        ),
    ]
