# Generated by Django 5.2.6 on 2025-09-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disciplines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answers",
            name="owner",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="owner",
            field=models.ForeignKey(
                blank="True",
                help_text="Выберите преподавателя",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.lesson",
                verbose_name="Курс",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="owner",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="answers",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.quiz",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="studentanswers",
            name="answer",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.answers",
                verbose_name="Ответ",
            ),
        ),
        migrations.AddField(
            model_name="studentanswers",
            name="owner",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AddField(
            model_name="studentanswers",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.quiz",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="educational_module",
            field=models.ForeignKey(
                blank="True",
                help_text="Выберите модуль",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="disciplines.educationalmodule",
                verbose_name="Образовательный модуль",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="topic",
            field=models.ForeignKey(
                blank="True",
                help_text="Выберите образовательную тему",
                null="True",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="disciplines.topic",
                verbose_name="Тема",
            ),
        ),
    ]
