# Generated by Django 5.2.6 on 2025-09-12 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disciplines", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="disciplines.lesson",
                verbose_name="Занятие",
            ),
        ),
    ]
